/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#b6c4ff",
        "on-surface-variant": "#c3c5d8",
        "primary-fixed": "#dce1ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#5c5fea",
        "primary-container": "#2563ff",
        "on-surface": "#dfe2f3",
        "error": "#ffb4ab",
        "on-primary-fixed": "#00164f",
        "on-secondary": "#003822",
        "outline-variant": "#434656",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dfe2f3",
        "inverse-on-surface": "#2c303d",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed-variant": "#003baf",
        "on-primary-container": "#f7f6ff",
        "on-background": "#dfe2f3",
        "on-error": "#690005",
        "surface-dim": "#0f131f",
        "surface-container": "#1b1f2c",
        "tertiary": "#c0c1ff",
        "secondary-fixed-dim": "#4cdf9d",
        "secondary-fixed": "#6dfcb7",
        "primary": "#b6c4ff",
        "surface-variant": "#313442",
        "surface-container-high": "#262a37",
        "on-tertiary": "#1000a9",
        "surface-container-lowest": "#0a0e1a",
        "on-secondary-container": "#004028",
        "secondary": "#4cdf9d",
        "outline": "#8d90a2",
        "background": "#0f131f",
        "error-container": "#93000a",
        "surface-container-highest": "#313442",
        "on-secondary-fixed": "#002112",
        "surface-container-low": "#171b28",
        "on-primary": "#00287d",
        "secondary-container": "#00b779",
        "on-tertiary-fixed": "#07006c",
        "surface-bright": "#353946",
        "on-secondary-fixed-variant": "#005234",
        "inverse-primary": "#004fe5",
        "on-tertiary-container": "#f8f5ff",
        "surface": "#0f131f",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#2f2ebe"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "unit": "4px",
        "stack-xs": "4px",
        "container-max": "1280px",
        "stack-xl": "64px",
        "stack-md": "16px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
